const { withAndroidManifest } = require('@expo/config-plugins');

module.exports = function withWidgetExported(config) {
  return withAndroidManifest(config, async (config) => {
    const androidManifest = config.modResults;
    const receivers = androidManifest.manifest.application[0].receiver;

    if (receivers) {
      receivers.forEach((receiver) => {
        // Find any widget receivers generated by react-native-android-widget
        if (receiver.$['android:name'] && receiver.$['android:name'].startsWith('.widget.')) {
          // Force them to be exported so the Android OS Widget Picker can see them
          receiver.$['android:exported'] = 'true';
        }
      });
    }
    return config;
  });
};
